version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: adonis_db
      MYSQL_USER: adonis_user
      MYSQL_PASSWORD: adonis_password
    ports:
      - "3370:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  mysql_data:
  redis_volume: