version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: adonis_db
      MYSQL_USER: adonis_user
      MYSQL_PASSWORD: adonis_password
    ports:
      - "3370:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    command: dumb-init node --inspect=0.0.0.0 ace serve --watch

volumes:
  mysql_data:
  redis_volume:























# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#     volumes:
#       - .:/home/node/app
#     ports:
#       - 3333:3333
#     depends_on:
#       - mysql

#   redis:
#     container_name: redis
#     image: redis:6-alpine
#     volumes:
#       - redis_volume:/data
#     ports:
#       - 6379:6379

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: adonis_db
#       MYSQL_USER: adonis_user
#       MYSQL_PASSWORD: adonis_password
#     ports:
#       - "3370:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
#   redis_volume:

# services:


#   adonis_app:
#     container_name: adonis_app
#     restart: always
#     build:
#       context: .
#       target: dependencies
#     ports:
#       - 3333:3333
#       - 9229:9229
#       - 5171:5171
#     # env_file:
#     #   - .env
#     volumes:
#       - ./:/home/node/app
#     command: ["node", "ace", "serve", "--watch"]
#     environment:
#       - NODE_ENV=development
#       - HOST=localhost
#       - PORT=3333
#       - DB_CONNECTION=mysql
#       - DB_HOST=mysql
#       - DB_PORT=3370
#       - DB_USER=adonis_user
#       - DB_PASSWORD=adonis_password
#       - DB_DATABASE=adonis_db
#       - APP_KEY=your_app_key_here
#       - LOG_LEVEL=info
#       - SESSION_DRIVER=cookie
#     depends_on:
#       - mysql
#       - redis


